name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Download and install PowerShell
      run: |
        $url = $env:POWERSHELL_URI
        $output = "$env:TEMP\pwsh.zip"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath "$env:TEMP\pwsh"
        $msiFile = Get-ChildItem -Path "$env:TEMP\pwsh" -Filter "*.msi" -Recurse | Select-Object -First 1
        Start-Process -Wait -FilePath msiexec.exe -ArgumentList "/i `"$($msiFile.FullName)`" /quiet"
    - name: Increment version and create tag
      run: |
        pwsh -File IncrementVersionGithub.ps1
    - name: Build & Restore
      run: dotnet build --configuration Release src/ChristopherBriddock.SortingAlgorithms.sln -p:PackageVersion=$env:VERSION_NUMBER
    - name: Publish
      run: dotnet publish src/ChristopherBriddock.SortingAlgorithms/ChristopherBriddock.SortingAlgorithms.csproj -c Release -p:PackageVersion=$env:VERSION_NUMBER
    - name: Create the package
      run: dotnet pack --configuration Release src/ChristopherBriddock.SortingAlgorithms/ChristopherBriddock.SortingAlgorithms.csproj -p:PackageVersion=$env:VERSION_NUMBER
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ChristopherBriddock.SortingAlgorithms
        path: src/ChristopherBriddock.SortingAlgorithms/bin/Release/net7.0/publish
        if-no-files-found: error
    - name: NuGet push
      run: dotnet nuget push "src/ChristopherBriddock.SortingAlgorithms/bin/Release/*.nupkg" -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
