name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Increment version and create tag
      run: |
        # Run the increment_version_script.sh shell script
        chmod +x increment_version_script.sh
        ./increment_version_script.sh

        # Get the new version from the project file (e.g., .csproj)
        version=$(dotnet msbuild -property:Version -nologo -t:PrintVersion src/ChristopherBriddock.SortingAlgorithms/ChristopherBriddock.SortingAlgorithms.csproj)
        echo "New version: $version"

        # Create a new Git tag with the version number
        git tag "$version"
        git push --tags
    - name: Build & Restore
      run: dotnet build --configuration Release src/ChristopherBriddock.SortingAlgorithms.sln
    - name: Publish
      run: dotnet publish src/ChristopherBriddock.SortingAlgorithms/ChristopherBriddock.SortingAlgorithms.csproj -c Release
    - name: Create the package
      run: dotnet pack --configuration Release src/ChristopherBriddock.SortingAlgorithms/ChristopherBriddock.SortingAlgorithms.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ChristopherBriddock.SortingAlgorithms
        path: src/ChristopherBriddock.SortingAlgorithms/bin/Release/net7.0/publish
        if-no-files-found: error
    - name: NuGet push
      run: dotnet nuget push "src/ChristopherBriddock.SortingAlgorithms/bin/Release/*.nupkg" -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
